[package]
name = "mimesis"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[dependencies]
glium = "*"
fps_clock = "*"
libc = "*"

[replace]
"glutin:0.7.4" = { git = 'https://github.com/thiolliere/glutin', branch = '0.7.4' }
# "glutin:0.7.4" = { path = "../glutin" }
